FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD four.jar /opt/four/
EXPOSE 8080
WORKDIR /opt/four/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "four.jar"]
